server:
  port: 8761

spring:
  application:
    name: discoveryservice

# Discovery service would not be registered as a client
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
