server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/MinseoKangQ/spring-cloud-config
#          username: [your username]
#          password: [your password]
#          uri: file:///Users/kangminseo/Documents/GitHub_Project/git-local-repo