server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/GitHub_Project/native-file-repo
        git:
          default-label: main
          uri: https://github.com/MinseoKangQ/spring-cloud-config
#          username: [your username]
#          password: [your password]
#          uri: file:///Users/kangminseo/Documents/GitHub_Project/git-local-repo